shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.urls import path
from . import views

app_name = 'shopping'
urlpatterns = [
    path('', views.home, name='主页'),
    path('<每个类别_id>/', views.SampleCategory, name='单类页'),
    path('<每个类别_id>/<每个商品_id>', views.detail, name='详情页'),
]

shopping/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    名称 = models.CharField(max_length=50, unique=True)
    描述 = models.TextField(blank=True)
    图片 = models.ImageField(upload_to='category', blank=True)

    class Meta:
        verbose_name_plural = '商品类别表'
        db_table = '商品类别表'

    def __str__(self):
        return self.名称


class Productlist(models.Model):
    名称 = models.CharField(max_length=100, unique=True)
    描述 = models.TextField(blank=True)
    图片 = models.ImageField(upload_to='category', blank=True)
    所属类别 = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    价格 = models.DecimalField(max_digits=10, decimal_places=2)
    库存 = models.IntegerField(default=0)
    已上架 = models.BooleanField(default=True)
    创建时间 = models.DateField(auto_now_add=True)
    修改时间 = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '产品列表'
        db_table = '产品列表'
        ordering = ('-创建时间',)

    def __str__(self):
        return self.名称

shopping/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory,Productlist

# Create your views here.
def home(request):
    all_Category = ProductCategory.objects.all()
    CategoryAndProducts = []
    for Eachcategory in all_Category:
        CategoryAndProducts.append((Eachcategory, Productlist.objects.filter(所属类别=Eachcategory, 已上架=True)[:1]))
    content = {"类别与商品": CategoryAndProducts, "所有类别":all_Category}
    return render(request,'shopping/home.html', content)

def SampleCategory(request, 每个类别_id):
    all_Category = ProductCategory.objects.all()
    all_need_Category =get_object_or_404(ProductCategory, id=每个类别_id)
    CategoryAndProducts = [(all_need_Category, Productlist.objects.filter(所属类别=all_need_Category, 已上架=True)[:2])]
    content = {"类别与商品": CategoryAndProducts, "所有类别":all_Category}
    return render(request,'shopping/home.html', content)

def detail(request, 每个类别_id, 每个商品_id):
    all_Category = ProductCategory.objects.all()
    Product =get_object_or_404(Productlist, id=每个商品_id ,已上架=True)
    content = {"商品": Product, "所有类别":all_Category}
    return render(request,'shopping/detail.html', content)

shopping/templates/shopping/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="{% block 关键词 %}小米,小米9，小米MIX,手机{% endblock 关键词 %}">
    <meta name="descriptions" content="{% block 网页描述 %}小米手机商城页面{% endblock 网页描述 %}">
    <title>{% block 网页标题 %}小米商城{% endblock 网页标题 %}</title>
</head>
<body>

    {% include 'shopping/header.html' %}
    {% include 'shopping/nav.html' %}

    <main>
        {% block 主体 %}
        这是主体
        {% endblock 主体 %}
    </main>
    {% include 'shopping/footer.html' %}


</body>
</html>

shopping/templates/shopping/detail.html
{% extends 'shopping/base.html' %}
{% load static %}

{% block 关键词 %}{{ 商品.名称 }}{% endblock 关键词 %}
{% block 网页描述 %}{{ 商品.描述 }}{% endblock 网页描述 %}
{% block 网页标题 %}{{ 商品.名称 }}立即购买-小米商城{% endblock 网页标题 %}

{% block 主体 %}
    <h2>
        {{ 商品.名称 }}
    </h2>
    <br>
    <p>{{ 商品.描述 }}</p>
    <br>
    <img src="{{ 商品.图片.url }}" alt="{{ 商品.名称 }}">

    {% if 商品.库存 > 0 %}
        <p>库存：{{ 商品.库存 }}个</p>
    {% else %}
        <p>暂时缺货</p>
    {% endif %}

    <h4>价格：{{ 商品.价格|cut:'.00' }}元</h4>
{% endblock 主体 %}

shopping/templates/shopping/footer.html
<footer>
    <center>&copy;小米商城，版权所有</center>
</footer>

shopping/templates/shopping/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'images/mi_logo.png' %}" alt="小米logo">
    </center>
</header>

shopping/templates/shopping/home.html
{% extends 'shopping/base.html' %}
{% load static %}

{% block 主体 %}


    {% for 每个类别, 该类商品 in 类别与商品 %}
        <h2>{{ 每个类别.名称 }}</h2>
        <img src="{{ 每个类别.图片.url }}" alt="{{ 每个类别.名称 }}">

        {% for 每件商品 in 该类商品 %}
            <h3><a href="{% url 'shopping:详情页' 每个类别.id 每件商品.id %}">{{ 每件商品.名称 }}</a></h3>
            <p>{{ 每件商品.描述 }}</p>
            <br>
            <img src="{{ 每件商品.图片.url }}" alt="{{ 每个类别.名称 }}">
            <br>
            <h4>{{ 每件商品.价格|cut:'.00' }}元</h4>
            <br>
        {% endfor %}

    {% endfor %}

{% endblock 主体 %}

shopping/templates/shopping/nav.html
<nav>
    <a href="{% url 'shopping:主页' %}">所有商品</a>
     {% for 每个类别 in 所有类别 %}
         <a href="{% url 'shopping:单类页' 每个类别.id %}">{{ 每个类别.名称 }}</a>
    {% endfor %}


    <a href="#">购物车</a>
</nav>